version: 2
project_name: cookie-guard-spoa

release:
  github:
    owner: artefactual-labs
    name: cookie-guard-spoa

builds:
  - id: cookie-guard-spoa
    main: ./cmd/cookie-guard-spoa
    binary: cookie-guard-spoa
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  abbrev: 8

nfpms:
  - id: default
    package_name: cookie-guard-spoa
    formats: [deb, rpm]
    vendor: Artefactual Systems Inc.
    homepage: https://github.com/artefactual-labs/cookie-guard-spoa
    maintainer: Artefactual Systems Inc. <info@artefactual.com>
    description: HAProxy SPOE agent that issues and verifies Cookie Guard tokens.
    license: Apache-2.0
    bindir: /usr/local/bin
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    contents:
      - src: systemd/cookie-guard-spoa.service
        dst: /etc/systemd/system/cookie-guard-spoa.service
        type: config
      - src: packaging/default/cookie-guard-spoa
        dst: /etc/default/cookie-guard-spoa
        type: config
      - src: haproxy/cookie-guard-spoa.cfg
        dst: /etc/haproxy/cookie-guard-spoa.cfg
        type: config
      # Challenge page (ALTCHA)
      - src: web/altcha_challenge.html.lf
        dst: /etc/haproxy/altcha_challenge.html.lf
        type: config
      # ALTCHA JS asset (versioned) and VERSION file; ensure these paths exist in the repo
      - src: web/assets/altcha
        dst: /etc/haproxy/assets/altcha
        type: tree
      # BotD JS asset (versioned) and VERSION file; served via /assets/botd/active/botd.esm.js
      - src: web/assets/botd
        dst: /etc/haproxy/assets/botd
        type: tree
    dependencies:
      - haproxy
    scripts:
      postinstall: packaging/nfpm/postinstall.sh
      preremove: packaging/nfpm/preremove.sh
      postremove: packaging/nfpm/postremove.sh
